require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orders", type: :request do
  # Order. As you add validations to Order, be sure to
  # adjust the attributes here as well.
  let!(:admin) { create(:admin) }
  let(:food) { create(:food) }
  let(:drink) { create(:drink) }
  let(:valid_attributes) {
    { customer_name: "customer", address: "av. JP n. 45", items_attributes: [
      { food_id: food.id, name: food.name, price: 13.23, quantity: 2 },
      { drink_id: drink.id, name: drink.name, price: 4.50, quantity: 3 },
    ] }
  }

  let(:invalid_attributes) {
    { items_attributes: [
      { food_id: food.id, name: food.name, price: 13.23, quantity: -1 },
      { drink_id: drink.id, name: drink.name, price: 4.50, quantity: 3 },
    ] }
  }

  before do
    sign_in admin
  end

  describe "GET /index" do
    it "renders a successful response" do
      Order.create! valid_attributes
      get orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order = Order.create! valid_attributes
      get order_url(order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      order = Order.create! valid_attributes
      get edit_order_url(order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Order" do
        expect {
          post orders_url, params: { order: valid_attributes }
        }.to change(Order, :count).by(1)
      end

      it "redirects to the created order" do
        post orders_url, params: { order: valid_attributes }
        expect(response).to redirect_to(order_url(Order.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Order" do
        expect {
          post orders_url, params: { order: invalid_attributes }
        }.to change(Order, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post orders_url, params: { order: invalid_attributes }
        expect(response).to render_template(:new)
      end
    end
  end

  describe "PATCH /update" do
    let(:order) { Order.create(valid_attributes) }

    context "with valid parameters" do
      before do
        valid_attributes[:items_attributes].first[:quantity] = 1
      end

      it "updates the requested order" do
        patch order_url(order), params: { order: valid_attributes }
        order.reload
        expect(order.items.first.quantity).to eq(1)
      end

      it "redirects to the order" do
        patch order_url(order), params: { order: valid_attributes }
        order.reload
        expect(response).to redirect_to(order_url(order))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        order = Order.create! valid_attributes
        patch order_url(order), params: { order: invalid_attributes }
        expect(response).to render_template(:edit)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested order" do
      order = Order.create! valid_attributes
      expect {
        delete order_url(order)
      }.to change(Order, :count).by(-1)
    end

    it "redirects to the orders list" do
      order = Order.create! valid_attributes
      delete order_url(order)
      expect(response).to redirect_to(orders_url)
    end
  end
end
