SENDGRID_API_KEY: ASK-THE-SENIOR-THE-SECRET-KEY-SAY-FRIEND-AND-COME-IN-GENDALF-THE-GREY

#twilio
TWILIO_ACCOUNT_ID: #examplekey
TWILIO_AUTH_TOKEN: #examplekey

#cloudinary
CLOUD_NAME: cloud_name
CLOUD_API_KEY: '12121212121212'
CLOUD_API_SECRET: not_real_number4d4dfd5